# Generated by Django 3.2.2 on 2021-08-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About_S',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('p', models.CharField(max_length=255)),
                ('text_1', models.CharField(max_length=255)),
                ('text_2', models.CharField(max_length=255)),
                ('text_3', models.CharField(max_length=255)),
                ('img', models.ImageField(blank=True, upload_to='img')),
            ],
        ),
        migrations.CreateModel(
            name='Counts_S',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Obunachilar', models.CharField(max_length=255)),
                ('Musics', models.CharField(max_length=255)),
                ('Homiylar', models.CharField(max_length=255)),
                ('Albomlar', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Features_S',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('text_1', models.CharField(max_length=255)),
                ('text_2', models.CharField(max_length=255)),
                ('text_3', models.CharField(max_length=255)),
                ('text_4', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Hero_S',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img')),
                ('title', models.CharField(max_length=255)),
                ('p', models.CharField(max_length=255)),
                ('link_name', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pricing_S',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('text_1', models.CharField(max_length=255)),
                ('text_2', models.CharField(max_length=255)),
                ('text_3', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Questions_S',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text_1', models.CharField(max_length=255)),
                ('text_2', models.CharField(max_length=255)),
                ('text_3', models.CharField(max_length=255)),
                ('text_4', models.CharField(max_length=255)),
                ('text_5', models.CharField(max_length=255)),
                ('text_6', models.CharField(blank=True, max_length=255)),
                ('text_7', models.CharField(blank=True, max_length=255)),
                ('text_8', models.CharField(blank=True, max_length=255)),
                ('text_9', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
