# Generated by Django 3.2.2 on 2021-09-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('sond_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('singer', models.CharField(max_length=255)),
                ('tags', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='img')),
                ('song', models.FileField(upload_to='img')),
            ],
        ),
    ]
